### ISSUE TITLE
Compatibility issue with SA-MP - GUI does not show properly

### ISSUE THREAD

**Issue by BianPrive** [Hemry81/GTASA-Remix#10]
In SA-MP 0.3 DL, the input box for the chat, player/tab screen, minimap and weapon icon do not show.
The ones that do show are the money counter and the chat log.

When you select a weapon and take aim the minimap returns briefly untill aiming stops.

**Comment by Hemry81** [comment]
The mod itself is not responsible for the UI elements; it's an issue with Remix. You may need to manually mark the UI text as UI texture. Additionally, the mod primarily focuses on the vanilla single-player experience and does not support any mods outside of our mod list or any SAMP games. If you encounter textures that shouldn't be there or if they display correctly, it likely depends on whether there are hash collision problems with the original game or other mods. If you have any issues with the mod, it's best to ask in the Discord Channel for a quicker response. Thank you.
