### ISSUE TITLE
White Cars

### ISSUE THREAD

**Issue by showdownking17** [Hemry81/GTASA-Remix#11]
When following all the directions for installation, all cars are white any fix for this. I have a RTX ready card.

**Comment by Hemry81** [comment]
The details for the temporary fix for the white car issue are in the RTX-Remix GTASA Discord channel.
RTX-Remix Discord Channel: [RTX-Remix Discord Channel](https://discord.gg/rtxremix)
GTASA Remix Discord Group: [RTX-Remix GTASA Discord Group](https://discord.com/channels/1028444667789967381/1097105394821759006). (To join this group, you first need to join the RTX-Remix Discord channel.)

**Comment by Hemry81** [comment]
SARemix Vehicle Toolkit script completely fix this problem
