### ISSUE TITLE
game crashes while loading a new game

### ISSUE THREAD

**Issue by rafciu41** [Hemry81/GTASA-Remix#12]
[gta_sa.exe_2024-08-01_00-22-12.log](https://github.com/user-attachments/files/16447701/gta_sa.exe_2024-08-01_00-22-12.log)

**Comment by Hemry81** [comment]
Try removing the mods in the mod loader one by one to find out which one is causing the problem. Or, you can try removing the RTX-Remix mod by renaming the "rtx-remx" folder to something like "rtx-remix1" to see if it's an issue with the Remix mod or if another mod is conflicting with it.
